#!/usr/bin/env python3

import http.server
import os
import socketserver

PORT = 8080

web_dir = os.path.join(os.path.dirname(__file__), 'web')
os.chdir(web_dir)

class Handler(http.server.SimpleHTTPRequestHandler):
    pass

Handler.extensions_map['.wasm'] = 'application/wasm'
Handler.extensions_map['.mjs'] = 'application/javascript'

httpd = socketserver.TCPServer(('', PORT), Handler)

print('serving at port', PORT)
try:
    httpd.serve_forever()
except KeyboardInterrupt:
    print('exiting')
    httpd.shutdown()
